### PR TITLE
Updates and box fix

### PR DESCRIPTION
**Pull request by Vectrobe**
Updated to work with modern changes, and the classic box replaced with a custom one for texture consistency

### CODE REVIEW

**Comment by Vectrobe** [comment]
image

**Comment by exaskye** [comment]
Thanks for your contribution; I'm currently moving across the country and will give this a closer look and release it once I've finished that.

-------- Original Message --------

**Comment by exaskye** [comment]
Oops, I forgot about this. I finished moving ~3 days ago.

I've [stopped modding](https://sleeping.town/@unascribed/101231022141008320) so I'll just merge this as-is without testing it or correcting style like I was going to. It'll be available on the [Elytra CI](https://ci.elytradev.com/view/all/job/elytra/job/DynamicDynamos/job/1.12.2/).

**Comment by Vectrobe** [comment]
you want to shift curse ownership to me so I can push updates? same details as my github

**Comment by exaskye** [comment]
Sorry, I don't know you at all, and am not comfortable giving full permission for the project over to a stranger.

I've finally pushed this as a release to Curse; I'm shifting to merging PRs and handling releases but not doing active dev or community management.

**Pull request merged**
